name: Build, Publish & Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  REPOSITORY: portfolio 
  IMAGE: static-site
  SHA: ${{ github.sha }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}'

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@master

    - name: Authorize Docker Push
      run: gcloud auth configure-docker

    - name: Build and Tag Docker Image
      run: docker build -t gcr.io/$PROJECT_ID/$REPOSITORY/$IMAGE:$SHA .

    - name: Push Docker Image to Google Container Registry
      run: docker push gcr.io/$PROJECT_ID/$REPOSITORY/$IMAGE:$SHA

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $REPOSITORY \
          --image gcr.io/$PROJECT_ID/$REPOSITORY/$IMAGE:$SHA \
          --platform managed \
          --region $REGION \
          --quiet